url:  http://tracehelms.com
name: Trace Helms
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.ruby-version']

markdown: redcarpet
pygments: true
permalink: pretty
sass:
  syntax: scss        # scss|sass
  style:  nested  # nested|expanded|compact|compressed
