url:  http://tracehelms.com
name: Trace Helms
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.ruby-version']
collections:
- projects

markdown: redcarpet
permalink: "/:categories/:title"
sass:
  sass_dir: assets/css
  style:  compressed  # nested|expanded|compact|compressed
  syntax: scss        # scss|sass
